# Copyright 2016 Nidium Inc. All rights reserved.
# Use of this source code is governed by a MIT license
# that can be found in the LICENSE file.

include ../../../config.mk

include ../../libs.mk

SRC_FILE=./src/base64_decode_fuzz.cpp
OBJ_FILE=$(TMP_DIR)/base64_decode_fuzz.o
BIN_FILE=$(TMP_DIR)/base64_decode_fuzz

include ../../../common.mk

