# Copyright 2016 Nidium Inc. All rights reserved.
# Use of this source code is governed by a MIT license
# that can be found in the LICENSE file.

include ../../../config.mk

include ../../libs.mk

SRC_FILE=./src/useragent_getos.cpp
OBJ_FILE=$(TMP_DIR)/useragent_getos.o
BIN_FILE=$(TMP_DIR)/useragent_getos_fuzz

include ../../../common.mk

