INPUT_DIR=./idl
OUTPUT_DIR=./cpp
PARAMS=-- --foo --foobar=1

CPP_DIRS=\
	$(OUTPUT_DIR)/DB.code \
	$(OUTPUT_DIR)/Console.code \
	$(OUTPUT_DIR)/Image.code \
	$(OUTPUT_DIR)/Process.code \
	$(OUTPUT_DIR)/OS.code \
	$(OUTPUT_DIR)/WebSocket.code \
	$(OUTPUT_DIR)/WebSocketClient.code \
	$(OUTPUT_DIR)/WebGL.code \
	$(OUTPUT_DIR)/Thread.code \
	$(OUTPUT_DIR)/Stream.code \
	$(OUTPUT_DIR)/Socket.code \
	$(OUTPUT_DIR)/Modules.code \
	$(OUTPUT_DIR)/HTTPServer.code \
	$(OUTPUT_DIR)/HTTP.code \
	$(OUTPUT_DIR)/Global.code \
	$(OUTPUT_DIR)/File.code \
	$(OUTPUT_DIR)/FS.code \
	$(OUTPUT_DIR)/Document.code \
	$(OUTPUT_DIR)/Debugger.code \
	$(OUTPUT_DIR)/Debug.code \
	$(OUTPUT_DIR)/Canvas2DContext.code \
	$(OUTPUT_DIR)/Canvas.code \
	$(OUTPUT_DIR)/AV.code \
	
	#$(OUTPUT_DIR)/Window.code \

all: $(CPP_DIRS)

include ../common.mk

