[
    Constructor(DOMString bar, optional unsigned short foo),
    classname = Hello
] interface Hello {
      attribute DOMString bar;
      attribute unsigned short foo;
     boolean foobar(unsigned short foo);
};
